StrangeFlix/urls.py
from django.contrib import admin 
from django.urls import path, include 
from login import views as user_view 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'),name = 'home'),
    path('login/',include('login.urls'), name = 'signin'),
    path('signup/',include('signup.urls'), name = 'signup'),
    path('accounts/', include('allauth.urls')),
    path('uploads/',include('videoplayer.urls'),name='videoplayer'),
    path('category/',include('category.urls'),name='videocats'),
    path('subscriptions/',include('subscriptions.urls'),name='plans'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

category/urls.py
from django.urls import path, include
from . import views

app_name = 'category'

urlpatterns = [
    path('',views.CategoryList,name = 'list'),
    path('comment/',views.videoComments,name = 'video-comment'),
    path('<slug:slug>/',views.CategoryView,name = 'detail'),
    path('<category_slug>/<categoryvideo_slug>/',views.Category_video,name = 'video-detail'),
]

home/urls.py
from django.urls import path, include
from . import views
from subscriptions.views import cancelSubscription

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),  
    path('index/', views.strange, name="strange"),
    path('profile/',views.profile, name="profile"),
    path('profile/cancel/',cancelSubscription, name="cancel"),
    path('profile/pay/',views.pay, name="pay"),
    # path('videos/',views.Video,name = 'video')
]

signup/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # path('', views.users_signup, name='signup'),
    # path('signup/',views.users_signup,name="signup"),
    # path('verify/',views.otp_verification,name="verify"),
]

subscriptions/urls.py
from django.urls import path

from . import views

app_name = 'subscriptions'
urlpatterns = [
    path('',views.membership,name = 'select'),
    path('plan/',views.selected_plan,name = 'plan'),
    path('plan/payment/',views.PaymentView,name = 'payment'),
    path('plan/payment/update/<Subscription_id>/',views.updateTransactions,name = 'update'),
]

videoplayer/urls.py
from django.urls import path, include
from . import views

app_name = 'videoplayer'

urlpatterns = [
    path('youtube/', views.youtube_search, name='Utube_search'),  
    path('youtube/download/', views.youtube_down, name='Utube_down'),
    path('device/',views.DeviceUpload,name = 'DevUpload'),  
    path('device/<slug:slug>/',views.detail_view, name = 'detail'),  
    path('tag/<slug:slug>/',views.tagged,name = 'tagged'),  
    # path('upload/', views.upload, name='upload'),

    # path('index/', views.strange, name="strange"),
]

category/models.py
from django.db import models
from subscriptions.models import Membership
from videoplayer.models import DeviceVideo, YtVideo
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=100)
    description = models.TextField()
    allowed_membership = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("category:detail", kwargs={"slug": self.slug})

    @property
    def videos(self):
        return self.video_set.all().order_by('position')



class Video(models.Model):
    slug = models.SlugField()
    device_video = models.ForeignKey(DeviceVideo,default=None,on_delete=models.CASCADE,null=True,blank=True)
    yt_video = models.ForeignKey(YtVideo,default=None,on_delete=models.CASCADE,null=True,blank=True)
    vid_category = models.ForeignKey(Category,on_delete=models.SET_NULL,null =True)
    position = models.IntegerField()
    
    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("category:video-detail", kwargs={"category_slug": self.vid_category.slug,"categoryvideo_slug":self.slug})

    @property
    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()


class Comment(models.Model):
    post = models.ForeignKey(Video,on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.user) + ', ' + self.post.slug[:40]

signup/models.py
from django.db import models

# Create your models here.

signup/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 
from allauth.account.forms import SignupForm
from django import forms 
  
# A Custom user registration form with added fields
class UserRegisterForm(UserCreationForm):
 
    username = forms.CharField(max_length = 20) 
    password = forms.CharField(max_length=20)
    email = forms.EmailField() 
    phone_no = forms.CharField(max_length = 20) 
    # first_name = forms.CharField(max_length = 20) 
    # last_name = forms.CharField(max_length = 20)
    class Meta: 
        model = User 
        fields = ['username', 'email', 'phone_no', 'password1','password2'] 


class SimpleSignupForm(SignupForm):
    phone = forms.CharField(max_length=12, label='Phone Number', widget=forms.TextInput(attrs={'placeholder': 'Phone Number'}))
    def save(self, request):
        user = super(SimpleSignupForm, self).save(request)
        user.phone = self.cleaned_data['phone']
        user.save()
        return user

category/views.py
from django.shortcuts import render, redirect
from .models import Video, Category ,Comment
from django.urls import reverse
from subscriptions.models import UserMembership
from django.http import HttpResponseRedirect
# Create your views here.

video_obj =""

def CategoryList(request):
    categories = Category.objects.all()
    context = {'objects':categories}
    return render(request,'category.html',context)

def CategoryView(request,slug):
    category_qs = Category.objects.filter(slug=slug)
    # print(category_qs)
    if category_qs.exists():
        category = category_qs.first()
    else:
        category = None
    # print(category)
    if category:
        videos_qs = category.videos.all()
    else:
        videos_qs= None
    # print(videos_qs)
    # categories = Video.objects.filter()
    context = {'objects':videos_qs}
    return render(request,'category_videos.html',context)

def Category_video(request,category_slug,categoryvideo_slug,*args, **kwargs):
    category_qs = Category.objects.filter(slug = category_slug)
    # print(category_qs)
    if category_qs.exists():
        category = category_qs.first()
    # print(category)

    videos_qs = category.videos.filter(slug = categoryvideo_slug)
    # print(videos_qs)
    if videos_qs.exists():
        video = videos_qs.first()
        global video_obj
        video_obj =video

    user_membership = UserMembership.objects.filter(user=request.user).first()
    user_membership_type = user_membership.membership.membership_type

    category_allowed_mem_type = category.allowed_membership.all()

    context = {'objects': None,}
    if category_allowed_mem_type.filter(membership_type=user_membership_type).exists():
        context = {'objects':video}

    if request.method == "POST":
        content = request.POST.get('content')
        created_comment = Comment(post=video,user=request.user,content=content)
        created_comment.save()
    
    video_comments = Comment.objects.filter(post=video).order_by('date_posted')
    context['comments'] = video_comments


    return render(request,'video.html',context)

def videoComments(request):
    if request.method == "POST":
        global video_obj
        content = request.POST.get('content')
        created_comment = Comment(post=video_obj,user=request.user,content=content)
        created_comment.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

signup/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout,login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
import requests
from django.http import JsonResponse
from django.contrib import messages
import random
from .forms import UserRegisterForm

# Create your views here.
data_session = ''

def signup(request):
    return render(request,'signup.html')

def users_signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        pass_1 = request.POST.get('password')
        # pass_2 = request.POST.get('password2')
        print(username)
        print(email)
        print(phone)
        print(pass_1)
        user = authenticate(request, username=username, password=pass_1)
        if user:
            login(request, user)
            messages.success(request, f' wecome {username} !!')
            return HttpResponseRedirect("/")
        elif pass_1:
            
            api_key_anurag = '55c5a679-08bf-11eb-9fa5-0200cd936042'
            url = "http://2factor.in/API/V1/" +api_key_anurag+ "/SMS/" + phone + "/AUTOGEN/OTPSEND"
            response = requests.request("GET", url)
            data = response.json()
            global data_session
            data_session = data['Details']
            # otp_session_data is stored in session.
            user = User.objects.create_user(username=username,
                                              email=email,
                                              password=pass_1,
                                             )
            user.is_active = True
            user.save()
            return HttpResponseRedirect('/signup/verify/')
    else:
         return render(request, 'signup.html')


# To verify Phone number of the user using SMS otp verfication

def otp_verification(request):
    if request.method == 'POST':
        user_otp = request.POST['OTP']
        # print(user_otp)
        global data_session
        url = 'http://2factor.in/API/V1/55c5a679-08bf-11eb-9fa5-0200cd936042/SMS/VERIFY/' + data_session + "/" + user_otp + ""
        response = requests.request('GET',url)
        data = response.json()
        # print(data)
        if data['Status'] =='Success':
            return HttpResponseRedirect('/') 
        else:
            return render(request,'verify.html',{'message':'Wrong OTP'})
    else:
        return render(request,'verify.html')

templates/category.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
{% for object in objects %}
<a href="{{object.get_absolute_url}}" class='text-white'> {{ object }} </a>
{% endfor %}
</div>
{% endblock content %}

templates/category_videos.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
{% for object in objects %}
<a href="{{ object.get_absolute_url }}" class='text-white'> {{ object }} </a>
{% endfor %}
</div>
{% endblock content %}

templates/checkout.html
<!-- This is the checkout Template -->

{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">

{% endblock head %}

{% block content %}

<div class="container">
  <div class="row">
    <h1>Payment</h1>
    <div class="col-sm-5 col-md-5">
      <p> Selected Membership: {{selected_membership}}</p>
      <p> Monthly Membership price: Rs.{{price}} <small>/month</small></p>


      <button onclick="toggleDisplay();" class="btn btn-warning" style="width: 100%;">Checkout with a credit
        card</button>
      <div id="collapseStripe" class="wrapper">
        <script src="https://js.stripe.com/v3/"></script>

        <form action="." method="post" id="payment-form">
          {% csrf_token %}
          <div class="form-row">
            <label for="card-element">
              Credit or debit card
            </label>
            <div id="card-element" class="StripeElement StripeElement--empty">
              <div class="__PrivateStripeElement"
                style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame3"
                  allowpaymentrequest="true"
                  src="https://js.stripe.com/v3/elements-inner-card-8a434729e4eb82355db4882974049278.html#style[base][color]=%2332325d&amp;style[base][lineHeight]=18px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;features[noop]=false&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js%2Felements%2Fquickstart&amp;controllerId=__privateStripeController0"
                  title="Secure payment input frame"
                  style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 18px;"></iframe><input
                  class="__PrivateStripeElement-input" aria-hidden="true"
                  style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;"><input
                  class="__PrivateStripeElement-safariInput" aria-hidden="true" tabindex="-1"
                  style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
              </div>
            </div>

            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
          </div>

          <button>Submit Payment</button>
        </form>

      </div>

    </div>

    <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>


  </div>
</div>


<!-- script for the stripe form -->
<script src="{% static 'js/checkout.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- script for toggling display of the form -->
<script type="text/javascript">
  function toggleDisplay() {
    var x = document.getElementById("collapseStripe");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  };
</script>

{% endblock content %}

{% block extra_body %}


{% endblock extra_body %}

templates/device.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="/static/css/tagsinput.css" />
{% endblock %}


{% block content %}
        <div class="container pt-5">
            
            <form  enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" id="myBtn" name="title" placeholder="Add title">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea type="text" class="form-control" id="myBtn" name="description" placeholder="Add description"></textarea>
                </div>
                <div class="form-group">
                    <label>Tags</label>
                    <input type="text" data-role="tagsinput" class="form-control" name="tags">
                </div>
                <div class="form-group">
                    <label>Video</label>
                    <input type="file" id="myFile" name="videofile" accept="video/*">
                </div>
                <div class="form-group">
                    <label>Thumbnail</label>
                    <input type="file" id="img" name="thumbnail" accept="image/*">
                </div>

                <button type="submit" class="btn btn-primary" id="myBtn">Submit</button>
            </form>
            <br>
            <p>Common Tags: 
            {% for mt in common_tags %}
                <a href="#" class="badge badge-success">{{mt}}</a>
            {% endfor %}
            </p>
            <div class="row mb-2 posts">
                    {% for video in videos %}
                    <div class="col-md-6">
                        <div class="cards">
                            <div class="row no-gutters border rounded  flex-md-row mb-4 shadow-sm h-md-250">
                                <div class="col p-4 d-flex flex-column position-static">
                                    <video width='400' poster="{{ MEDIA_URL }}{{ video.thumbnail }}" controls>
                                        <source src='{{ MEDIA_URL }}{{ video.videofile }}' type='video/mp4'>
                                    </video>
                                    <h3 class="my-1"><a href="{% url 'videoplayer:detail' video.slug %}">{{video.title}}</a></h3>
                                    <div style="display:flex">
                                        {% for tag in video.tags.all %}
                                        <a href="{% url 'videoplayer:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                    <p class="mb-auto">{{video.description}}</p>
                                </div>
                            </div>
                        </div>       
                    </div>
                    {% endfor %}
            </div>
        
        </div>    
{% endblock content %}









{% block extra_body %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="/static/js/tagsinput.js"></script>
    <script>
        var input = document.getElementById("myInput");
        input.addEventListener("keyup", function(event) {
          if (event.keyCode === 13) {
           event.preventDefault();
           document.getElementById("myBtn").click();
          }
        });
    </script>


    <script>  
    $("#post-form").submit(function(e){
        e.preventDefault();
        });</script>
{% endblock %}

templates/memberships.html
{% extends 'base.html' %}
{% block head %}
{% endblock  %}

{% block content %}
<div class="container">
    <h1>Select a membership</h1>
    <div class="row">
        {% for object in objects %}
        <div class="col-sm-4 col-md-4">
            <h1>{{object.membership_type}}</h1>
            <p>Price: Rs.{{object.price}}<small>/month</small></p>
            <h3>Included Categories</h3>
            <ul>
                {% for categori in object.category_set.all  %}
                <li class="text-white">{{categori.title}}</li>
                {% endfor %}
            </ul>
            <form method="POST" action='{% url 'subscriptions:plan' %}'>
                {% csrf_token %}
                {% if object.membership_type != current_membership %}
                <button class="btn btn-warning">Select</button>
                {% else %}
                <h5> This is Your current membership</h5>
                {% endif %}
                <input type="hidden" name="membership_type" value="{{ object.membership_type }}">

            </form>


        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/video_cat.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
{% comment %} {% for object in objects %} {% endcomment %}
{% if objects is not None %}
<p class='text-white'> {{ objects.yt_video.title }} </p>
<video width='400' controls >
    <source src='{{ MEDIA_URL }}{{ objects.yt_video.ytubevideo }}' type='video/mp4'>
</video>
{% else %}
<div class="alert alert-danger" role="alert">
  Cannot Watch this Video! Upgrade Membership
</div>
{% endif %}
{% comment %} {% endfor %} {% endcomment %}
</div>
{% endblock content %}

templates/youtube.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% endblock %}

{%block title%} YoutubeDownloader {% endblock %}

</head>
{% block content %}
<section id="top">
    <div class="container-fluid">
        <div class="row c" style="background-color:#03aa94;">
            <div class="col-sm-12 mt-2" style="font-family:'Montserrat'; color: aliceblue; font-size: 35px;">
                <center><b>Welcome to YouTube video downloader</b></center>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row" style="margin-top:50px;">
            <div class="col-sm-6">
                <h4>Steps to download YouTube video :-</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6" style="font-family:'Montserrat'; color: rgb(174, 174, 175); font-size: 15px;" >
                <ul>
                    <li>Step 1 : Copy the video URL in the text box</li>
                    <li>Step 2 : Click on the Search button</li>
                    <li>Step 3 : Choose the available format and resolution</li>
                    <li>Step 4 : Click on Download button</li>
                </ul>
            </div>
            <div class="col-sm-1">

            </div>
            <div class="col-sm-3" id="myDiv" style="font-family:'Montserrat'; color:aliceblue; font-size: 15px;">
                <div aria-live="polite" aria-atomic="true">
                    <div class="toast">
                        <div class="toast-header">
                            <strong class="mr-auto">Notifications</strong>
                            <button id="hide" type="button" style="color:aliceblue;" class="ml-2 mb-1 close" data-dismiss="toast"
                                aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <br>
                            <small>1 seconds ago</small>
                            
                        </div>
                        <div class="toast-body text-white">
                            <br>
                            Downloading starts ...
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3" id="myDiv2" style="font-family:'Montserrat'; color: aliceblue; font-size: 15px;">
                <div aria-live="polite" aria-atomic="true">
                    <div class="toast">
                        <div class="toast-header">
                            <strong class="mr-auto">Notifications</strong>
                            <button id="hide" type="button" style="color:aliceblue;" class="ml-2 mb-1 close" data-dismiss="toast"
                                aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <br>
                            <small>1 seconds ago</small>
                            
                        </div>
                        <div class="toast-body">
                            <br>
                            {% if msg %}
                            {{msg}}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <hr>
            </div>
        </div>
        <form class="" action="{% url 'videoplayer:Utube_search' %}" method="POST">
            <div class="row" >

                {% csrf_token %}
                <div class="col-sm-6" style="margin-top:20px;">
                    {% if video_url %}
                    <input class="form-control" type="search" name="video_url" placeholder="Enter url" aria-label="Search"
                        value={{video_url}}>
                    {% else %}
                    <input class="form-control" type="search" name="video_url" placeholder="Enter url" aria-label="Search">
                    {% endif %}
                </div>
                <div class="col-sm-2" style="margin-top:20px;">
                    <button class="btn btn-outline-success"  type="submit" >Search</button>
                </div>

            </div>
        </form>
        <br>
        <form class="" action="{% url 'videoplayer:Utube_down' %}" method="POST">
            {% csrf_token %}
            <div class="row mt-3 section">
                <div class="col-sm-3">
                    {% if thumbnail_url %}
                    <img src="{{thumbnail_url}}" alt="" width="100%">
                    <p id="title" style="margin-top:5px;"><b>{{title}}</b></p>
                    {% endif %}
                </div>
                <div class="col-sm-9 section">
                    <div class="row">
                        <div class="col-sm-5">
                            <h5>Select Format</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-2 text-white">
                            <label><input type="radio" name="formatRadio" value="audio"> Audio</label>
                        </div>
                        <div class="col-sm-2 text-white">
                            <label><input type="radio" name="formatRadio" value="video"> Video</label>
                        </div>
                    </div>
                    <div class="row">
                        <br>
                    </div>
                    <div class="row video">
                        <div class="col-sm-5">
                            <h5>Select Video Quality</h5>
                        </div>
                    </div>
                    <div class="row video">
                        <div class="col-sm-2 text-white">
                            <label><input type="radio" name="qualityRadio" value="1080p"> High</label>
                        </div>
                        <div class="col-sm-2 text-white">
                            <label><input type="radio" name="qualityRadio" value="720p"> Medium</label>
                        </div>
                        <div class="col-sm-2 text-white">
                            <label><input type="radio" name="qualityRadio" value="360p"> Low</label>
                        </div>

                    </div>
                    <div class="row">
                        <br>
                    </div>
                    <div class="row">
                        <input type="hidden" name="video_url_d" value={{video_url}}>
                    </div>
                    <div class="row section">
                        <div class="col-sm-3 ml-4 ">
                            <button class="btn download text-white" id="show"><i class="fa fa-download"></i> Download</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
<br><br>

{% endblock %}

{% block extra_body %}
<script>
    $(".video").hide()
    $("#myDiv").hide();
    $("#myDiv2").hide();
    console.log("{{thumbnail_url}}");
    if ($('#title').html() === undefined) {
        $(".section").hide();
    }
    $(document).ready(function () {
        $("#hide2").click(function () {
            $("#myDiv2").hide();
        });
    });
    if ("{{msg}}".length != 0) {
        $("#myDiv2").show();
    }
    $(document).ready(function () {
        $("#hide").click(function () {
            $("#myDiv").hide();
        });
        $("#show").click(function () {
            $("#myDiv").show();
        });
    });
    // $('div.section:empty').hide();
    $(document).ready(function () {
        $('input[type="radio"]').click(function () {
            var inputValue = $(this).attr("value");
            if (inputValue == "audio") {
                // var targetBox = $("." + inputValue);
                $(".video").hide();
                // $(".download").hide();
            }
            else {
                var targetBox = $("." + inputValue);
                // $(".box").not(targetBox).hide();
                $(targetBox).show();
            }
        });
    });
</script>
{% endblock %}